image:
  name: ribose/metanorma
  entrypoint: [""]

cache:
  paths:

build:
  stage: build
  script:
    - bundle
    - make clean all
    - mkdir -p public && mv *.xml *.html public/
  artifacts:
    paths:
      - public
