sudo: true
language: ruby
rvm:
  - 2.5.1
cache: bundler
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y git make ruby-bundler ruby-dev libxml2-dev libxslt-dev default-jre graphviz
  - travis_retry gem install bundler
  - travis_retry gem install nokogiri -v '1.8.4'
  - sudo mkdir -p /opt/plantuml
  - cd /opt/plantuml
  - sudo curl -JLO ${PLANTUML_URL}
  - printf '#!/bin/sh\njava -jar /opt/plantuml/plantuml.jar "$@"\n' > /usr/local/bin/plantuml
  - sudo chmod a+x /usr/local/bin/plantuml
env:
  - JAVA_OPTS="java.awt.headless=true"
  - PLANTUML_URL=http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
script:
  # - plantuml -testdot
  - make clean all
