
[[introduction]]
== Introduction

=== Background

DevOps, the practice of applying developmental practices on infrastructure operations, has been shown to positively impact efficiencies of operation teams today. Given its strengthening adoption, it is a logical next step in applying those practices to the arena of security, as well as considering its impact on security itself.

=== Application to security

While DevOps is now broadly practiced, it has been generally separated from security practices.

As with any problem, without a proper definition there cannot be a correct answer. Unfortunately, there is currently no standardized term in industry that cater to this aspect. Some members of the community have developed several makeshift terms that attempt to explain the intersection of security and DevOps, or the amalgamation of security, development and operations, including “DevOpsSec”, “DevSecOps”, “SecDevOps”.

There are multiple proposed terms that attempt to combine Security with DevOps, but are widely conflicting in definition. Terms such as DevSecOps, DevOpsSec, SecDevOps have been used interchangeably but the meanings they convey can be completely different and are not thought further beyond a mix-mash of words. For a global and wider industry audience, it is crucial to correct, clarify and standardize such terms.

In addition, there is no industry recognized definition of security automation leading to confusion and misinterpretations.


=== External pressure to organizations

Organizations today are faced with multiple issues, including:

* spiralling compliance governance costs;
* global shortage of cyber security professionals, which forces organizations to more efficiently utilize staff;
* the notable disconnect between strategic security and operational security.

All of these factors force the organization to deliver more bang for less buck.


=== Purpose

This whitepaper is an attempt to clarify and standardize an authoritative definition of the intersection between the three aspects of security, development and operations, and use it to generalize the principles of a novel security management approach we call “Agile Security”. Several approaches to Agile Security are suggested to resolve the availability gap of cyber security professionals.
