
[[introduction]]
== Introduction

=== Background

DevOps, the practice of applying developmental practices on infrastructure operations, has been shown to positively impact efficiencies of operation teams today, especially in the cloud environment.

Given its strengthening adoption, it is a logical next step in applying those practices to the arena of security management, as well as considering its impact on security itself.

=== Application to security

DevOps is now broadly practiced but it has been generally separated from security practices. There is currently no standardized term in industry that cater to this aspect.

To explain the intersection of security and DevOps, as well as the amalgamation of security, development and operations practices, a number of terms have been proposed by members of community, including "`DevOpsSec`", "`DevSecOps`", "`SecDevOps`".

These terms have been used mostly interchangeably, but the meanings they convey can be vastly different. The definitions of these terms can widely conflict with each other depending on the particular understanding of the reader.

Moreover, there is no industry recognized definition for security automation, which is a core concept to the application of DevOps practices to security operations, leading to confusion and misinterpretations.

It is therefore crucial to clarify and standardize such terms for a global and wider industry audience.


=== External pressure to organizations

Organizations today are faced with a number of security management issues, including:

* spiralling compliance governance costs;

* Faster to market - deployment

* Complex hybrid and cross cloud solutions

* Limited security skills in DevOps

* global shortage of cyber security professionals, which forces organizations to more efficiently utilize staff;

* the notable disconnect between strategic security and operational security.

All of these factors force an organization to deliver more security more effectively and efficiently.


=== Purpose

This whitepaper aims to clarify and standardize an authoritative definition of the intersection between the three aspects of security, development and operations, and use it to generalize the principles of a novel security management approach we call "`Agile Security`".

Several approaches to Agile Security are suggested to resolve the availability gap of cyber security professionals.
