
[[agile-sec]]
== Agile Security: the new paradigm

Problem: CSO's do not have sufficient number of security staff.

//[ TODO: Describe the ITIL operational gap ]

Agile Security is a new paradigm for information security management, that emphasizes embodiment of security across organizational roles, reactive to external and internal threats in an agile and dynamic way.

NOTE: Agile Security compares to Agile Software Development, similar to how the traditional ISMS approach compares to the Waterfall methodology.

Agile Security is about dynamic information exchange within the organization  **** Is this really so ****. Like the immune system of the human body, information is immediately propagated to adjacent, potentially vulnerable functions given detection of a threat. A traditional ISMS approach will require that threat information be reported back to the higher functions before any response is made. With Agile Security, the business functions themselves are integrated security functions and can provide an immediate response to block potential impact. A centralized response is important, but should not prohibit an immediate tactical approach.

The ISMS approach is about adopting best practices. However, often best practices that work in larger organizations do not work with smaller ones, and create an unnecessary burden for the smaller organizations, which takes away precious time and effort from daily work and hence negatively affects their security stances.
**** break down the paragraph in smaller chunks ****

Agile Security solves the security skill shortage paradox by promoting the idea of "`hybrid-domain-security-experts`".

* Risks are delegated
**** what does this mean ****

* Security responsibilities are delegated or automated

A "`commitment`" of top leadership (as in ISMS) is not enough. Top leadership must understand the nature of security and be committed to integrating security into each and every aspect of the organization. Top leadership must fully understand the risks and threats the organization faces (its risk profile) with regards to security, and set clear boundaries and requirements for personnel to adhere to.

Humans, it is often said, are the weakest link in security. Phishing, social engineering are all techniques to trick an unsuspecting individual to voluntarily compromise security of an organization. Without full participation (not just "`awareness`") of all involved people, security cannot be achieved.

