
[[agile-pillars]]
== Six pillars of Agile Security

=== Collectively responsible

Everyone is responsible for the security stance of the organization. The CSO plays a leadership and shepherding role for information security within an organization, but each person has their own security responsibility, and they must contribution (and potential problems) towards the organization's security stance. Edge users are not just "`security-aware`", but are the first line of defence.
// what does edge mean - not defined

=== Collaborate

Security can only be achieved through collaboration, not confrontation. A security aware and collaborative culture is necessary for the foot soldiers to report potential anomalies. The human factor is often the weakest link and that most security incidents are caused by simple human error.

=== Pragmatic

Security should provide value, not hindrance. For every security initiative or adopted security control, a cost-benefit should be considered to allow transparency on the value of security. Without this pragmatic approach, it is too easy for persons unaware of the benefits of security to dismiss security practices as mere overhead or unnecessary. This provides the necessary business case to convince stakeholders of security requirements and confidence to execute plans effectively.
// Firsst part needs review 

Traditional ISMS can create overhead, and needs balanced tailoring to an organization and adoption of best practices. Documentation requirements should be based on clearly thought out value brought to the organization, not a hard requirement.
// Where does this really go, maybe not here 


=== Integrate

Security must be integrated in every aspect of the business. Dedicated security personnel rarely have in-depth domain expertise similar to your business domain experts. The truth is, no one else will know your domain, as well as its risks, as your business domain experts. A team of dedicated security experts will most likely be oblivious to your domain-specific security issues. Domain knowledge and security knowledge must be fused and co-exist in every organizational process for effective security management.

=== Automate

Automated security practices are the core of optimizing process efficiency. Processes that can be automated should be automated, and those that can't should be transformed. Automation also creates its own set of problems but automated approaches to those problems are often possible. There is a saying in software development: if you do the same thing thrice, it's time to program it, and this applies similarly with Agile Security
// what does transfirmed mean 

=== Measure

Performance that cannot be measured cannot be improved. Without measurements, there is no formal evidence whether information security management is effective. Agile Security is about achieving results, and even as vague as they might be, the results must be measurable for transparency and improvement.
