
[appendix]
== Guidelines for implementing Agile Security

=== Approach A: Cross-train

Form an operational security function by selecting 1 or 2 persons that have an interest or background in security from each Business Unit and delegate security related tasks to those individuals. Make these persons a representative of the operational security teams.

The operational security teams know exactly what types of operating systems are used, applications are supported for the business, etc. In some organizations, this collaboration involves embedding IT operations specialists within software development teams, thus forming a cross-functional team. This effort may also be combined with a skills matrix.


=== Approach B: Delegate

Delegate risk management, maintenance of BCPs etc. to department heads. Freeing up resources of the dedicated security team so they can focus on the security process management and providing the framework(s). The department heads know exactly what they have in house, what risks there are.

DevOps is process neutral. Organizations can use Agile or Scrum. Have security engineers attend daily scrum meetings, make them part of the DevOps team.
**** seems a little out of context ****

////
=== Spiraling governance costs

Lower costs by using security automation

Operating system patching results in downtime due to the sheer volume of patches and patching can result in unplanned downtime due to inability to test patches across the chain.

////
